trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

name: Chrismo_Sitemap_0_1_$(Rev:r)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $buildName = "$(Build.BuildNumber)"
      $buildnumber = $buildName.replace("Chrismo_Sitemap_0_1_", "0.1.")
      echo "##vso[task.setvariable variable=appVersion;]$buildnumber"

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test Chrismo.Sitemap.Tests'
  inputs:
    command: 'test'
    projects: 'src/Chrismo.Sitemap.Tests/Chrismo.Sitemap.Tests.csproj'
    arguments: '--logger trx --collect "Code coverage"'
    testRunTitle: 'dotnet test Chrismo.Sitemap.Tests'
    
- script: dotnet tool install --global dotnet-sonarscanner
  displayName: 'Install sonar scanner'

- script: dotnet sonarscanner begin /k:"ChrismoNL_Chrismo-Sitemap-Generator" /o:"chrismo" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(Sonar.Login)" /d:sonar.branch.name="$(Build.SourceBranchName)" /d:sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)\*.trx /d:sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)\**\*.coverage
  displayName: 'Begin dotnet sonar scanner'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build Chrismo.Sitemap'
  inputs:
    command: 'build'
    projects: 'src/Chrismo.Sitemap/Chrismo.Sitemap.csproj'
    arguments: '--configuration $(buildConfiguration) -p:Version=$(appVersion)'

- script: dotnet sonarscanner end /d:sonar.login="$(Sonar.Login)"
  displayName: 'End dotnet sonar scanner'

- script: dotnet pack src/Chrismo.Sitemap/Chrismo.Sitemap.csproj -p:Version=$(appVersion) -p:PackageVersion=$(appVersion) --configuration $(BuildConfiguration) --no-restore --no-build --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack Chrismo.Sitemap'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'