trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

name: Chrismo_Sitemap_0_1_$(Rev:r)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        $buildName = "$(Build.BuildNumber)"
        $buildnumber = $buildName.replace("Chrismo_Sitemap_0_1_", "0.1.")
        echo "##vso[task.setvariable variable=appVersion;]$buildnumber"

- script: dotnet test src/Chrismo.Sitemap.Tests/Chrismo.Sitemap.Tests.csproj --logger trx --collect "Code coverage"
  displayName: 'dotnet test Chrismo.Sitemap.Tests' 

- task: PublishTestResults@2
  displayName: 'Publish test results' 
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build Chrismo.Sitemap'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) -p:Version=$(appVersion)'
    projects: 'src/Chrismo.Sitemap/Chrismo.Sitemap.csproj'

- script: dotnet pack src/Chrismo.Sitemap/Chrismo.Sitemap.csproj -p:Version=$(appVersion) -p:PackageVersion=$(appVersion) --configuration $(BuildConfiguration) --no-restore --no-build --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack Chrismo.Sitemap'

- task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'chrismo-sitemap-packages' 